### ISSUE TITLE
Update this manuscript's thumbnail

### ISSUE THREAD

**Issue by vincerubinetti** [lelaboratoire/rethink-prs-ms#13]
Hello Manubot user.

If you were not already aware, your paper is being showcased in the [Manubot Catalog](https://manubot.org/catalog/).

Previously, we were making our own thumbnails for each paper, and hosting them in the same repository as `manubot.org`. But now we are moving to a system of having each paper store its thumbnail in its own repository, and linking to it from there.

Here is our suggested thumbnail for your paper that follows the new [thumbnail guidelines](https://github.com/manubot/catalog#thumbnail-guidelines):

![New Project](https://user-images.githubusercontent.com/8326331/64816429-aa814800-d575-11e9-93f6-650a89a886a4.png)

Please place this image *in the root of your repository* with the name `thumbnail.png`. Once you have, let us know in this issue and we'll do the rest to update the catalog.

**Comment by trangdata** [comment]
@vincerubinetti  I don't particularly love this figure, but I couldn't find a better thumbnail, so let's go with your suggestion. Completed in [this commit](https://github.com/lelaboratoire/rethink-prs-ms/commit/fe749d86108a06ecde45388fdd3ac2ef0719f744).
